package com.salat.gbinder.features.launcher

data class PermissionInfo(
    val title: String,
    val description: String,
    val type: String, // "runtime" or "appops"
    val opName: String // appops operation name (for appops type)
)

val PERMISSION_LIST = mapOf(
    "android.permission.REQUEST_DELETE_PACKAGES" to PermissionInfo("卸载应用", "允许卸载第三方应用", "appops", "REQUEST_DELETE_PACKAGES"),
    "android.permission.REQUEST_INSTALL_PACKAGES" to PermissionInfo("安装应用", "允许安装第三方应用", "appops", "REQUEST_INSTALL_PACKAGES"),
    "android.permission.SYSTEM_ALERT_WINDOW" to PermissionInfo("悬浮窗", "此应用可显示在其他应用上方或屏幕的其他部分", "appops", "SYSTEM_ALERT_WINDOW"),
    "android.permission.READ_EXTERNAL_STORAGE" to PermissionInfo("存储权限（读取）", "允许应用读取SD卡的内容", "runtime", "READ_EXTERNAL_STORAGE"),
    "android.permission.WRITE_EXTERNAL_STORAGE" to PermissionInfo("存储权限（写入）", "允许修改或删除SD卡中的内容", "runtime", "WRITE_EXTERNAL_STORAGE"),
    "android.permission.MANAGE_EXTERNAL_STORAGE" to PermissionInfo("存储权限（所有文件）", "管理所有文件", "runtime", "MANAGE_EXTERNAL_STORAGE"),
    "android.permission.READ_MEDIA_AUDIO" to PermissionInfo("音频文件（读取）", "允许读取内部存储中的音频文件", "runtime", "READ_MEDIA_AUDIO"),
    "android.permission.WRITE_MEDIA_AUDIO" to PermissionInfo("音频文件（写入）", "允许保存音频文件到内部存储", "runtime", "WRITE_MEDIA_AUDIO"),
    "android.permission.READ_MEDIA_VIDEO" to PermissionInfo("视频文件（读取）", "允许读取内部存储中的视频文件", "runtime", "READ_MEDIA_VIDEO"),
    "android.permission.WRITE_MEDIA_VIDEO" to PermissionInfo("视频文件（写入）", "允许保存视频文件到内部存储", "runtime", "WRITE_MEDIA_VIDEO"),
    "android.permission.READ_MEDIA_IMAGES" to PermissionInfo("照片文件（读取）", "允许读取内部存储中的图片文件", "runtime", "READ_MEDIA_IMAGES"),
    "android.permission.WRITE_MEDIA_IMAGES" to PermissionInfo("照片文件（写入）", "允许保存图片文件到内部存储", "runtime", "WRITE_MEDIA_IMAGES"),
    "android.permission.BIND_ACCESSIBILITY_SERVICE" to PermissionInfo("无障碍服务", "允许使用无障碍服务", "runtime", "BIND_ACCESSIBILITY_SERVICE"),
    "android.permission.WRITE_SETTINGS" to PermissionInfo("修改系统设置", "允许修改系统的设置数据", "appops", "WRITE_SETTINGS"),
    "android.permission.WRITE_SECURE_SETTINGS" to PermissionInfo("修改系统安全设置", "允许修改系统安全设置", "appops", "WRITE_SECURE_SETTINGS"),
    "android.permission.FOREGROUND_SERVICE" to PermissionInfo("前台服务", "允许在创建前台服务", "appops", "FOREGROUND_SERVICE"),
    "android.permission.RUN_IN_BACKGROUND" to PermissionInfo("后台服务", "允许应用在后台运行", "appops", "RUN_IN_BACKGROUND"),
    "android.permission.RUN_ANY_IN_BACKGROUND" to PermissionInfo("后台服务", "允许应用在后台任意运行", "appops", "RUN_ANY_IN_BACKGROUND"),
    "android.permission.QUERY_ALL_PACKAGES" to PermissionInfo("查询所有软件包", "允许查看所有已安装的软件包", "runtime", "QUERY_ALL_PACKAGES"),
    "android.permission.GET_USAGE_STATS" to PermissionInfo("使用统计", "允许获取使用情况统计信息", "appops", "GET_USAGE_STATS"),
    "android.permission.CHANGE_WIFI_STATE" to PermissionInfo("修改WiFi", "允许更改WLAN网络状态", "appops", "CHANGE_WIFI_STATE"),
    "android.permission.WAKE_LOCK" to PermissionInfo("唤醒锁", "允许保持屏幕常亮", "appops", "WAKE_LOCK"),
    "android.permission.CAMERA" to PermissionInfo("相机", "允许使用相机拍摄照片和录制视频", "appops", "CAMERA"),
    "android.permission.VIBRATE" to PermissionInfo("振动", "允许控制振动器", "appops", "VIBRATE"),
    "android.permission.READ_LOGS" to PermissionInfo("读取日志", "允许读取系统日志", "appops", "READ_LOGS"),
    "android.permission.READ_CLIPBOARD" to PermissionInfo("剪切板（读取）", "允许读取剪贴板内容", "appops", "READ_CLIPBOARD"),
    "android.permission.WRITE_CLIPBOARD" to PermissionInfo("剪切板（写入）", "允许写入剪贴板数据", "appops", "WRITE_CLIPBOARD"),
    "android.permission.POST_NOTIFICATION" to PermissionInfo("发送通知", "允许发送通知栏通知", "appops", "POST_NOTIFICATION"),
    "android.permission.READ_PHONE_STATE" to PermissionInfo("读取手机状态", "允许读取手机状态", "appops", "READ_PHONE_STATE"),
    "android.permission.READ_PHONE_NUMBERS" to PermissionInfo("读取电话号码", "允许读取电话号码", "runtime", "READ_PHONE_NUMBERS"),
    "android.permission.CALL_PHONE" to PermissionInfo("拨打电话", "允许拨打电话", "runtime", "CALL_PHONE"),
    "android.permission.ANSWER_PHONE_CALLS" to PermissionInfo("接听电话", "允许接听来电", "runtime", "ANSWER_PHONE_CALLS"),
    "android.permission.READ_CALL_LOG" to PermissionInfo("读取通话记录", "允许读取通话记录", "appops", "READ_CALL_LOG"),
    "android.permission.WRITE_CALL_LOG" to PermissionInfo("写入通话记录", "允许写入通话记录", "runtime", "WRITE_CALL_LOG"),
    "android.permission.READ_CONTACTS" to PermissionInfo("读取联系人", "允许读取联系人", "appops", "READ_CONTACTS"),
    "android.permission.WRITE_CONTACTS" to PermissionInfo("写入联系人", "允许写入联系人", "runtime", "WRITE_CONTACTS"),
    "android.permission.READ_CALENDAR" to PermissionInfo("读取日历", "允许读取日历活动", "appops", "READ_CALENDAR"),
    "android.permission.WRITE_CALENDAR" to PermissionInfo("写入日历", "允许添加/删除日历活动", "runtime", "WRITE_CALENDAR"),
    "android.permission.READ_SMS" to PermissionInfo("读取短信", "允许读取短信", "appops", "READ_SMS"),
    "android.permission.SEND_SMS" to PermissionInfo("发送短信", "允许发送短信", "runtime", "SEND_SMS"),
    "android.permission.RECEIVE_SMS" to PermissionInfo("接收短信", "允许接收短信", "runtime", "RECEIVE_SMS"),
    "android.permission.RECORD_AUDIO" to PermissionInfo("录音", "允许使用麦克风录音", "appops", "RECORD_AUDIO"),
    "android.permission.ACCESS_FINE_LOCATION" to PermissionInfo("精确位置", "允许获取精确位置", "runtime", "ACCESS_FINE_LOCATION"),
    "android.permission.ACCESS_COARSE_LOCATION" to PermissionInfo("粗略位置", "允许获取大致位置", "runtime", "ACCESS_COARSE_LOCATION"),
    "android.permission.ACCESS_BACKGROUND_LOCATION" to PermissionInfo("后台位置", "允许在后台使用位置信息", "appops", "ACCESS_BACKGROUND_LOCATION"),
    "android.permission.BLUETOOTH_ADVERTISE" to PermissionInfo("蓝牙广播", "允许向附近蓝牙设备广播", "runtime", "BLUETOOTH_ADVERTISE"),
    "android.permission.BLUETOOTH_SCAN" to PermissionInfo("蓝牙扫描", "允许发现蓝牙设备", "runtime", "BLUETOOTH_SCAN"),
    "android.permission.BLUETOOTH_CONNECT" to PermissionInfo("蓝牙连接", "允许连接蓝牙设备", "runtime", "BLUETOOTH_CONNECT"),
    "android.permission.BODY_SENSORS" to PermissionInfo("身体传感器", "允许访问传感器数据", "runtime", "BODY_SENSORS"),
    "android.permission.ACTIVITY_RECOGNITION" to PermissionInfo("活动识别", "允许识别活动状态", "runtime", "ACTIVITY_RECOGNITION"),
    "android.permission.ACCESS_MEDIA_LOCATION" to PermissionInfo("媒体位置", "允许读取媒体文件位置信息", "runtime", "ACCESS_MEDIA_LOCATION"),
    "android.permission.SCHEDULE_EXACT_ALARM" to PermissionInfo("精确闹钟", "允许安排精确闹钟", "appops", "SCHEDULE_EXACT_ALARM"),
    "android.permission.USE_BIOMETRIC" to PermissionInfo("生物识别", "允许使用生物特征硬件", "runtime", "USE_BIOMETRIC"),
    "android.permission.GET_ACCOUNTS" to PermissionInfo("查找账户", "允许获取设备已知的账户列表", "runtime", "GET_ACCOUNTS"),
    "android.permission.GPS" to PermissionInfo("GPS", "允许使用GPS定位", "appops", "GPS"),
    "android.permission.TOAST_WINDOW" to PermissionInfo("Toast消息", "允许使用Toast消息提示", "appops", "TOAST_WINDOW"),
    "android.permission.ACTIVATE_VPN" to PermissionInfo("VPN", "允许激活VPN", "appops", "ACTIVATE_VPN"),
    "android.permission.TURN_ON_SCREEN" to PermissionInfo("唤醒屏幕", "允许开启屏幕显示", "appops", "TURN_ON_SCREEN"),
    "android.permission.DUMP" to PermissionInfo("获取DUMP信息", "允许获取系统dump信息", "appops", "DUMP"),
    "android.permission.BATTERY_STATS" to PermissionInfo("电池统计", "允许更新电池统计信息", "appops", "BATTERY_STATS"),
    "android.permission.MOCK_LOCATION" to PermissionInfo("模拟位置", "允许模拟位置信息", "appops", "MOCK_LOCATION"),
    "android.permission.READ_DEVICE_IDENTIFIERS" to PermissionInfo("设备标识", "允许访问IMEI等标识符", "appops", "READ_DEVICE_IDENTIFIERS"),
    "android.permission.INTERACT_ACROSS_USERS" to PermissionInfo("跨用户交互", "允许与用户互动", "runtime", "INTERACT_ACROSS_USERS")
,
    "android.permission.BIND_NOTIFICATION_LISTENER_SERVICE" to PermissionInfo("通知使用权", "允许读取通知栏通知", "runtime", "BIND_NOTIFICATION_LISTENER_SERVICE"),
    "android.permission.BIND_ACCESSIBILITY_SERVICE" to PermissionInfo("无障碍服务", "允许使用无障碍服务", "appops", "BIND_ACCESSIBILITY_SERVICE"),
)