package com.salat.gbinder.gmp;

import com.salat.gbinder.gmp.IMusicInfoListener;
import com.salat.gbinder.gmp.IMusicQueryCallback;
import com.salat.gbinder.gmp.IMusicStateListener;
import com.salat.gbinder.gmp.IMusicUserInfoListener;
import com.salat.gbinder.gmp.MusicInfo;

interface IMusicManager {
    void doPlay(int position, in MusicInfo musicInfo);
    void play();
    void pause();
    void pre();
    void next();
    void seekTo(long position);
    void fastForward(long time);
    void fastRewind(long time);
    void activeLastSource(boolean autoPlay);
    void getPlayList(IMusicInfoListener listener);
    void addFavor(String source);
    void cancelFavor(String source);
    void getFavor();
    int getCurrentPlayState(String source);
    boolean supportLastSource();
    long getCurrentPosition();
    void getCurrentMediaInfo(String source);
    void startApp();
    void setPlayMode(int playMode);
    int getPlayMode(String source);
    void requestSource();
    void getOnlineUserInfo(IMusicUserInfoListener listener);
    void addListener(IMusicStateListener stateListener, IMusicInfoListener infoListener, IMusicUserInfoListener userInfoListener);
    void getContent(String contentId, IMusicStateListener listener);
    void playContent(int type, String id, int position, boolean autoPlay);
    void setSource(String source, String extra);
    String getSource(String extra);
    void searchMusicByName(String keyword, IMusicStateListener listener);
    void playMusicByNameAndPosition(String name, int position);
    void openFavor();
    void openHistory();
    List getCommonUseSource(String source);
    void searchAndPlayMusicFromFlow(String keyword);
    void openChannelTab(String tab);
    void openPlayList();
    void playFavor();
    void semanticSearch(String keyword, String artist, String album, String extra);
    void semanticSearchV2(String keyword, IMusicQueryCallback callback);
    void screenChange(int screenState);
    void openLoginPage();
    void replayCurrent();
    void openLyric();
    void semanticSearchAndPlay(String keyword, in List words, String extra, boolean autoPlay, boolean fromVr, String scene, IMusicQueryCallback callback);
    void switchSourceQuality(int quality);
    void setSourceAndPlay(String source, boolean autoPlay, String extra);
    int onUIWordingTriggered(String wording);
    void closeLikeList();
    void openHistoryList(int type, boolean autoPlay);
    boolean isUserMusicVip();
    boolean isVipQuality(int quality);
    boolean isAgreedUserProtocol();
    int isSupportChangeMode(int source);
    boolean isMusicQualitySwitch(int quality);
    int notifyVrStatusNotifierStatus(int status);
    MusicInfo queryMediaInfoSync();
    String getAppAudioStatus(String source);
    void setFlowAudioStatus(boolean active);
}
